#!/bin/bash
# makes a text from the pdf
# word understands text and grammar :)

INPDF="$1"
OUTTXT="$2"

if [ -z "$INPDF" ]; then
	echo "Usage: $0 InPDF OutTXT"
	exit -1
fi

if [ -z "$OUTTXT" ]; then
        echo "Output will be written to ${INPDF}.txt"
	OUTTXT="${INPDF}.txt"
fi

if [ ! -f "$INPDF" ]; then
	echo "Seems like $INPDF is not a normal file or does not exist"
	exit -1
fi

pdftotext -nopgbrk -raw "$INPDF" "$OUTTXT"

#remove newline
sed -i ':a;N;$!ba;s/\n/ /g' $OUTTXT


#remove hyphenation
sed -i 's/- //g' $OUTTXT

#remove citations
sed -i -r 's/ \[[0-9]+(, *[0-9]*)*(\], \[[0-9]+)*\]//g' $OUTTXT
#roman citations
sed -i -r 's/\[[ivx]+\]//g' $OUTTXT

sed -i -r 's/ﬁ/fi/g' $OUTTXT
sed -i -r 's/ﬀ/ff/g' $OUTTXT
sed -i -r 's/ﬃ/ffi/g' $OUTTXT
sed -i -r 's/ﬄ/ffl/g' $OUTTXT
sed -i -r 's/ﬂ/fl/g' $OUTTXT


